language: ruby
bundler_args: --without development
rvm:
  - 2.1.1
branches:
  only:
    - master
notifications:
  recipients:
    - jamesdabbs@gmail.com
services:
  - mysql
before_script:
  - 'rake db:setup RAILS_ENV=test'
