language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
branches:
  only:
    - master
notifications:
  recipients:
    - jamesdabbs@gmail.com
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE brubeck_test;'