development:
  adapter:  mysql2
  socket:   /tmp/mysql.sock
  database: brubeck
  username: root
  password:
  pool:     5
  timeout:  5000

test:
  adapter:  mysql2
  socket:   /tmp/mysql.sock
  database: brubeck_test
  username: root
  password:
  pool:     5
  timeout:  5000

production:
  adapter:  mysql2
  database: brubeck_prod
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || 'OETuqwNbTNcsKGs2RAgJJ0E3' %>
  pool:     5
  timeout:  5000
