default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  timeout:  5000
  password:

development:
  <<: *default
  database: brubeck_dev

test:
  <<: *default
  database: brubeck_test

production:
  <<: *default
  database: brubeck_prod

legacy:
  adapter:  mysql2
  host:     localhost
  database: pi_base_legacy
  username: root
  password:
