default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  username: brubeck
  password:
  pool:     5
  timeout:  5000

development:
  <<: *default
  database: brubeck_dev

test:
  <<: *default
  database: brubeck_test

legacy:
  adapter:  mysql2
  host:     localhost
  database: pi_base_legacy
  username: root
  password:
