development:
  adapter:  postgresql
  socket:   /tmp/mysql.sock
  database: brubeck
  username: root
  password:
  pool:     5
  timeout:  5000

test: &test
  adapter:  postgresql
  database: brubeck_test
  username: root
  encoding: utf8

cucumber:
  <<: *test